test_glsl.frag
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 56

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 52 55
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "on"
                              Name 12  "two"
                              Name 17  "ret"
                              Name 25  "something"
                              Name 35  "i"
                              Name 52  "uv"
                              Name 55  "color"
                              Decorate 52(uv) Location 1
                              Decorate 55(color) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 3
               8:             TypePointer Function 7(fvec3)
              10:    6(float) Constant 1065353216
              11:    7(fvec3) ConstantComposite 10 10 10
              13:    6(float) Constant 0
              14:    7(fvec3) ConstantComposite 13 13 13
              15:             TypeBool
              16:             TypePointer Function 15(bool)
              20:             TypeVector 15(bool) 3
              23:             TypeInt 32 1
              24:             TypePointer Function 23(int)
              26:     23(int) Constant 3
              28:     23(int) Constant 2
              32:     23(int) Constant 10
              34:     23(int) Constant 14
              36:     23(int) Constant 0
              43:     23(int) Constant 5
              46:     23(int) Constant 1
              50:             TypeVector 6(float) 2
              51:             TypePointer Input 50(fvec2)
          52(uv):     51(ptr) Variable Input
              53:             TypeVector 6(float) 4
              54:             TypePointer Output 53(fvec4)
       55(color):     54(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
           9(on):      8(ptr) Variable Function
         12(two):      8(ptr) Variable Function
         17(ret):     16(ptr) Variable Function
   25(something):     24(ptr) Variable Function
           35(i):     24(ptr) Variable Function
                              Store 9(on) 11
                              Store 12(two) 14
              18:    7(fvec3) Load 9(on)
              19:    7(fvec3) Load 12(two)
              21:   20(bvec3) FOrdEqual 18 19
              22:    15(bool) All 21
                              Store 17(ret) 22
                              Store 25(something) 26
              27:     23(int) Load 25(something)
              29:    15(bool) SGreaterThan 27 28
                              SelectionMerge 31 None
                              BranchConditional 29 30 33
              30:               Label
                                Store 25(something) 32
                                Branch 31
              33:               Label
                                Store 25(something) 34
                                Branch 31
              31:             Label
                              Store 35(i) 36
                              Branch 37
              37:             Label
                              LoopMerge 39 40 None
                              Branch 41
              41:             Label
              42:     23(int) Load 35(i)
              44:    15(bool) SLessThan 42 43
                              BranchConditional 44 38 39
              38:               Label
              45:     23(int)   Load 25(something)
              47:     23(int)   IAdd 45 46
                                Store 25(something) 47
                                Branch 40
              40:               Label
              48:     23(int)   Load 35(i)
              49:     23(int)   IAdd 48 46
                                Store 35(i) 49
                                Branch 37
              39:             Label
                              Return
                              FunctionEnd