// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 35

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 29 33
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "kolorek"
                              Name 15  "colormaps"
                              Name 23  "colorsampler"
                              Name 29  "uv"
                              Name 33  "color"
                              Decorate 15(colormaps) DescriptorSet 0
                              Decorate 15(colormaps) Binding 1
                              Decorate 23(colorsampler) DescriptorSet 0
                              Decorate 23(colorsampler) Binding 0
                              Decorate 29(uv) Location 1
                              Decorate 33(color) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Function 7(fvec4)
              10:             TypeImage 6(float) 2D sampled format:Unknown
              11:             TypeInt 32 0
              12:     11(int) Constant 2
              13:             TypeArray 10 12
              14:             TypePointer UniformConstant 13
   15(colormaps):     14(ptr) Variable UniformConstant
              16:             TypeInt 32 1
              17:     16(int) Constant 0
              18:             TypePointer UniformConstant 10
              21:             TypeSampler
              22:             TypePointer UniformConstant 21
23(colorsampler):     22(ptr) Variable UniformConstant
              25:             TypeSampledImage 10
              27:             TypeVector 6(float) 2
              28:             TypePointer Input 27(fvec2)
          29(uv):     28(ptr) Variable Input
              32:             TypePointer Output 7(fvec4)
       33(color):     32(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
      9(kolorek):      8(ptr) Variable Function
              19:     18(ptr) AccessChain 15(colormaps) 17
              20:          10 Load 19
              24:          21 Load 23(colorsampler)
              26:          25 SampledImage 20 24
              30:   27(fvec2) Load 29(uv)
              31:    7(fvec4) ImageSampleImplicitLod 26 30
                              Store 9(kolorek) 31
              34:    7(fvec4) Load 9(kolorek)
                              Store 33(color) 34
                              Return
                              FunctionEnd
